Failed to import the site module
Traceback (most recent call last):
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 523, in main
    known_paths = addsitepackages(known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 320, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1273, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1231, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 556, in spec_from_file_location
  File "<frozen importlib._bootstrap>", line 373, in __init__
KeyboardInterrupt
