Failed to import the site module
Traceback (most recent call last):
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/sysconfig.py", line 609, in get_config_var
    return get_config_vars().get(name)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/sysconfig.py", line 558, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/yuntian/anaconda3/envs/main/lib/python3.6/sysconfig.py", line 429, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
KeyboardInterrupt
